# Generated by Django 6.0.1 on 2026-01-17 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('icon_color', models.CharField(default='#e31e24', max_length=20)),
                ('icon_text', models.CharField(blank=True, max_length=10)),
                ('mode_text', models.CharField(default='Online / Offline', max_length=100)),
                ('placement_text', models.CharField(default='100% Placement Support', max_length=100)),
                ('categories', models.TextField(help_text='Comma separated categories')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(upload_to='gallery/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('image', models.ImageField(upload_to='trainers/')),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('url', models.FileField(upload_to='gallery/items/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/')),
                ('title', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.gallerycategory')),
            ],
        ),
    ]
