# Generated by Django 6.0.1 on 2026-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutcontent_contactmessage_contactsetting_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
