# Generated by Django 5.2.7 on 2026-01-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mediaasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycategory',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/categories/'),
        ),
    ]
