# Generated by Django 5.2.7 on 2026-01-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gallerycategory_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enrollments/photos/')),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
                ('passing_year', models.CharField(max_length=10)),
                ('percentage', models.CharField(max_length=20)),
                ('selected_course', models.CharField(max_length=200)),
                ('course_type', models.CharField(max_length=50)),
                ('batch_timing', models.CharField(max_length=50)),
                ('experience_status', models.CharField(max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('payment_mode', models.CharField(default='UPI', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_amount', models.CharField(blank=True, max_length=50)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
