# Generated by Django 5.2.7 on 2026-01-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='objective',
            field=models.TextField(blank=True, default='To provide in-depth knowledge and practical skills.'),
        ),
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='scope',
            field=models.TextField(blank=True, default='High demand in the current market.'),
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
